### application-prod.properties
server.port=9092

# Spring Data JPA
spring.datasource.url=jdbc:postgresql://dpg-d8k59oflk1mc73af6qq0-a:5432/platzi_play_db_vn1d
spring.datasource.username=abraham
spring.datasource.password=KcLrHh8naMwWfNZQxqOotY1VZMHkQjjN

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

# langchain4j
langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.chat-model.base-url=http://langchain4j.dev/demo/openai/v1
langchain4j.open-ai.chat-model.enabled=true

