### application.properties
spring.profiles.active=dev

spring.application.name=abraham-play
server.servlet.context-path=/platzi-play/api

server.max-http-request-header-size=20KB

# PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update

# langchain4j
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.chat-model.base-url=http://langchain4j.dev/demo/openai/v1
langchain4j.open-ai.chat-model.enabled=true